mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$',views.results,name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
    #email url
    url(r'^email/$',views.mail,name='mail')
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.utils import timezone

from django.utils.encoding import python_2_unicode_compatible

import datetime

# Create your models here.
@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
    	return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


@python_2_unicode_compatible 
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
    	return self.choice_text

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Question, Choice
from django.http import Http404
from django.views import generic
from django.core.mail import send_mail





def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list}
	return render(request,'polls/index.html',context)

def detail(request, question_id):
	try:
		question = Question.objects.get(id=question_id)
		context = {'que':'','id':''}
		context['que']=question
		context['id']=question_id
	except Question.DoesNotExist:
		raise Http404("Question Doest not exist")

	return render(request,'polls/details.html',context)

def results(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/results.html',{'question': question})

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = Choice.objects.get(id=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request,'polls/details.html',{'que':question,'error_message':"you didnt select any choice"})
	else:
		selected_choice.votes+=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

#email view
def mail(request):
	res = send_mail("subject for test","this is message for test","misbah1307@gmail.com",["misbah1307@gmail.com"],fail_silently=False)
	return HttpResponse('%s'%res)

#Generic views
#class IndexView(generic.ListView):
#    template_name = 'polls/index.html'
#    context_object_name = 'latest_question_list'

#    def get_queryset(self):
#        """Return the last five published questions."""
#        return Question.objects.order_by('-pub_date')[:5]


#class DetailView(generic.DetailView):
#    model = Question
#    template_name = 'polls/details.html'


#class ResultsView(generic.DetailView):
#    model = Question
#    template_name = 'polls/results.html'

polls/templates/polls/details.html
<!DOCTYPE html>
<html>
<head>
	<title>Question Details of {{id}}</title>
</head>
<body>
<h1>{{ que }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' que.id %}" method="post">
	{% csrf_token %}
	{% for choice in que.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
	{%endfor%}
	<input type="submit" name="" value="vote">
</form>
<form action="{%url 'polls:mail' %}" method="post">
	{% csrf_token %}
	<input type="text" name="subject" id="subject"><br>
	<input type="textArea" name="message" id="message"><br>
	<input type="text" name="from" id="from"><br>
	<input type="text" name="mailto" id="mailto"><br>
	<input type="submit" name="mail him" value="mail">

</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
	<title>Results</title>
</head>
<body>


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>


</body>
</html>